// Chinese vocabulary lists by CEFR level and sub-level
// Based on HSK standards: A1≈HSK1, A2≈HSK2, B1≈HSK3-4, B2≈HSK4-5, C1≈HSK5-6
// Each sub-level introduces ~15 target words.
// Higher sub-levels build on earlier ones — prompts use the target list for the selected sub-level.

export interface VocabItem {
  zh: string      // Simplified Chinese characters
  pinyin: string  // Romanization with tone marks
  en: string      // English meaning
  pos: string     // Part of speech: n, v, adj, adv, pron, num, mw, conj, part, interj
}

export type VocabMap = Record<string, Record<number, VocabItem[]>>

export const CHINESE_VOCAB: VocabMap = {

  // ─────────────────────────────────────────────
  // A1  (HSK 1 — ~150 essential words)
  // ─────────────────────────────────────────────
  A1: {
    1: [
      // Greetings, core pronouns, politeness
      { zh: '你好', pinyin: 'nǐ hǎo', en: 'hello', pos: 'interj' },
      { zh: '再见', pinyin: 'zài jiàn', en: 'goodbye', pos: 'interj' },
      { zh: '谢谢', pinyin: 'xiè xie', en: 'thank you', pos: 'interj' },
      { zh: '不客气', pinyin: 'bú kè qi', en: "you're welcome", pos: 'interj' },
      { zh: '对不起', pinyin: 'duì bu qǐ', en: 'sorry', pos: 'interj' },
      { zh: '没关系', pinyin: 'méi guān xi', en: "it's okay / no problem", pos: 'interj' },
      { zh: '我', pinyin: 'wǒ', en: 'I / me', pos: 'pron' },
      { zh: '你', pinyin: 'nǐ', en: 'you', pos: 'pron' },
      { zh: '他', pinyin: 'tā', en: 'he / him', pos: 'pron' },
      { zh: '她', pinyin: 'tā', en: 'she / her', pos: 'pron' },
      { zh: '我们', pinyin: 'wǒ men', en: 'we / us', pos: 'pron' },
      { zh: '是', pinyin: 'shì', en: 'to be (am/is/are)', pos: 'v' },
      { zh: '不', pinyin: 'bù', en: 'no / not', pos: 'adv' },
      { zh: '的', pinyin: 'de', en: "possessive particle ('s)", pos: 'part' },
      { zh: '吗', pinyin: 'ma', en: 'question particle (yes/no)', pos: 'part' },
    ],
    2: [
      // Numbers and basic quantities
      { zh: '一', pinyin: 'yī', en: 'one', pos: 'num' },
      { zh: '二', pinyin: 'èr', en: 'two', pos: 'num' },
      { zh: '三', pinyin: 'sān', en: 'three', pos: 'num' },
      { zh: '四', pinyin: 'sì', en: 'four', pos: 'num' },
      { zh: '五', pinyin: 'wǔ', en: 'five', pos: 'num' },
      { zh: '六', pinyin: 'liù', en: 'six', pos: 'num' },
      { zh: '七', pinyin: 'qī', en: 'seven', pos: 'num' },
      { zh: '八', pinyin: 'bā', en: 'eight', pos: 'num' },
      { zh: '九', pinyin: 'jiǔ', en: 'nine', pos: 'num' },
      { zh: '十', pinyin: 'shí', en: 'ten', pos: 'num' },
      { zh: '零', pinyin: 'líng', en: 'zero', pos: 'num' },
      { zh: '多少', pinyin: 'duō shao', en: 'how many / how much', pos: 'pron' },
      { zh: '几', pinyin: 'jǐ', en: 'how many (small number)', pos: 'pron' },
      { zh: '个', pinyin: 'gè', en: 'general measure word', pos: 'mw' },
      { zh: '两', pinyin: 'liǎng', en: 'two (with measure words)', pos: 'num' },
    ],
    3: [
      // Family and people
      { zh: '爸爸', pinyin: 'bà ba', en: 'dad / father', pos: 'n' },
      { zh: '妈妈', pinyin: 'mā ma', en: 'mum / mother', pos: 'n' },
      { zh: '儿子', pinyin: 'ér zi', en: 'son', pos: 'n' },
      { zh: '女儿', pinyin: 'nǚ ér', en: 'daughter', pos: 'n' },
      { zh: '朋友', pinyin: 'péng you', en: 'friend', pos: 'n' },
      { zh: '同学', pinyin: 'tóng xué', en: 'classmate', pos: 'n' },
      { zh: '老师', pinyin: 'lǎo shī', en: 'teacher', pos: 'n' },
      { zh: '学生', pinyin: 'xué sheng', en: 'student', pos: 'n' },
      { zh: '先生', pinyin: 'xiān sheng', en: 'Mr / husband', pos: 'n' },
      { zh: '小姐', pinyin: 'xiǎo jiě', en: 'Miss / young woman', pos: 'n' },
      { zh: '人', pinyin: 'rén', en: 'person / people', pos: 'n' },
      { zh: '们', pinyin: 'men', en: 'plural suffix (people)', pos: 'part' },
      { zh: '谁', pinyin: 'shéi', en: 'who', pos: 'pron' },
      { zh: '叫', pinyin: 'jiào', en: 'to be called / to call', pos: 'v' },
      { zh: '认识', pinyin: 'rèn shi', en: 'to know (a person)', pos: 'v' },
    ],
    4: [
      // Food and drink
      { zh: '吃', pinyin: 'chī', en: 'to eat', pos: 'v' },
      { zh: '喝', pinyin: 'hē', en: 'to drink', pos: 'v' },
      { zh: '水', pinyin: 'shuǐ', en: 'water', pos: 'n' },
      { zh: '茶', pinyin: 'chá', en: 'tea', pos: 'n' },
      { zh: '菜', pinyin: 'cài', en: 'dish / vegetable', pos: 'n' },
      { zh: '饭', pinyin: 'fàn', en: 'cooked rice / meal', pos: 'n' },
      { zh: '面条', pinyin: 'miàn tiáo', en: 'noodles', pos: 'n' },
      { zh: '苹果', pinyin: 'píng guǒ', en: 'apple', pos: 'n' },
      { zh: '水果', pinyin: 'shuǐ guǒ', en: 'fruit', pos: 'n' },
      { zh: '好吃', pinyin: 'hǎo chī', en: 'delicious', pos: 'adj' },
      { zh: '杯子', pinyin: 'bēi zi', en: 'cup / glass', pos: 'n' },
      { zh: '饭店', pinyin: 'fàn diàn', en: 'restaurant / hotel', pos: 'n' },
      { zh: '东西', pinyin: 'dōng xi', en: 'thing / stuff', pos: 'n' },
      { zh: '买', pinyin: 'mǎi', en: 'to buy', pos: 'v' },
      { zh: '钱', pinyin: 'qián', en: 'money', pos: 'n' },
    ],
    5: [
      // Core action verbs
      { zh: '去', pinyin: 'qù', en: 'to go', pos: 'v' },
      { zh: '来', pinyin: 'lái', en: 'to come', pos: 'v' },
      { zh: '有', pinyin: 'yǒu', en: 'to have / there is', pos: 'v' },
      { zh: '没有', pinyin: 'méi yǒu', en: "to not have / there isn't", pos: 'v' },
      { zh: '看', pinyin: 'kàn', en: 'to look / to watch / to read', pos: 'v' },
      { zh: '听', pinyin: 'tīng', en: 'to listen / to hear', pos: 'v' },
      { zh: '说', pinyin: 'shuō', en: 'to say / to speak', pos: 'v' },
      { zh: '读', pinyin: 'dú', en: 'to read (aloud)', pos: 'v' },
      { zh: '写', pinyin: 'xiě', en: 'to write', pos: 'v' },
      { zh: '学习', pinyin: 'xué xí', en: 'to study / to learn', pos: 'v' },
      { zh: '工作', pinyin: 'gōng zuò', en: 'to work / work (n)', pos: 'v/n' },
      { zh: '睡觉', pinyin: 'shuì jiào', en: 'to sleep', pos: 'v' },
      { zh: '开', pinyin: 'kāi', en: 'to open / to drive', pos: 'v' },
      { zh: '回', pinyin: 'huí', en: 'to return / to go back', pos: 'v' },
      { zh: '住', pinyin: 'zhù', en: 'to live / to stay', pos: 'v' },
    ],
    6: [
      // Time basics
      { zh: '今天', pinyin: 'jīn tiān', en: 'today', pos: 'n' },
      { zh: '明天', pinyin: 'míng tiān', en: 'tomorrow', pos: 'n' },
      { zh: '昨天', pinyin: 'zuó tiān', en: 'yesterday', pos: 'n' },
      { zh: '现在', pinyin: 'xiàn zài', en: 'now', pos: 'n/adv' },
      { zh: '年', pinyin: 'nián', en: 'year', pos: 'n' },
      { zh: '月', pinyin: 'yuè', en: 'month / moon', pos: 'n' },
      { zh: '日', pinyin: 'rì', en: 'day / date', pos: 'n' },
      { zh: '星期', pinyin: 'xīng qī', en: 'week / weekday', pos: 'n' },
      { zh: '上午', pinyin: 'shàng wǔ', en: 'morning (before noon)', pos: 'n' },
      { zh: '下午', pinyin: 'xià wǔ', en: 'afternoon', pos: 'n' },
      { zh: '中午', pinyin: 'zhōng wǔ', en: 'noon / midday', pos: 'n' },
      { zh: '点', pinyin: 'diǎn', en: "o'clock", pos: 'mw' },
      { zh: '分钟', pinyin: 'fēn zhōng', en: 'minute', pos: 'n' },
      { zh: '时候', pinyin: 'shí hou', en: 'time / moment (when)', pos: 'n' },
      { zh: '号', pinyin: 'hào', en: 'date (of month) / number', pos: 'n' },
    ],
    7: [
      // Places and transport
      { zh: '家', pinyin: 'jiā', en: 'home / family', pos: 'n' },
      { zh: '学校', pinyin: 'xué xiào', en: 'school', pos: 'n' },
      { zh: '医院', pinyin: 'yī yuàn', en: 'hospital', pos: 'n' },
      { zh: '商店', pinyin: 'shāng diàn', en: 'shop / store', pos: 'n' },
      { zh: '中国', pinyin: 'Zhōng guó', en: 'China', pos: 'n' },
      { zh: '火车站', pinyin: 'huǒ chē zhàn', en: 'train station', pos: 'n' },
      { zh: '飞机', pinyin: 'fēi jī', en: 'airplane', pos: 'n' },
      { zh: '出租车', pinyin: 'chū zū chē', en: 'taxi', pos: 'n' },
      { zh: '坐', pinyin: 'zuò', en: 'to sit / to take (transport)', pos: 'v' },
      { zh: '在', pinyin: 'zài', en: 'at / in / to be at', pos: 'prep/v' },
      { zh: '里', pinyin: 'lǐ', en: 'inside / in', pos: 'n/part' },
      { zh: '上', pinyin: 'shàng', en: 'on / above / upper', pos: 'n/prep' },
      { zh: '下', pinyin: 'xià', en: 'under / below / lower', pos: 'n/prep' },
      { zh: '前面', pinyin: 'qián miàn', en: 'in front of / ahead', pos: 'n' },
      { zh: '后面', pinyin: 'hòu miàn', en: 'behind / at the back', pos: 'n' },
    ],
    8: [
      // Basic adjectives and feelings
      { zh: '大', pinyin: 'dà', en: 'big / large', pos: 'adj' },
      { zh: '小', pinyin: 'xiǎo', en: 'small / little', pos: 'adj' },
      { zh: '多', pinyin: 'duō', en: 'many / much / more', pos: 'adj' },
      { zh: '少', pinyin: 'shǎo', en: 'few / little / less', pos: 'adj' },
      { zh: '好', pinyin: 'hǎo', en: 'good / well', pos: 'adj' },
      { zh: '很', pinyin: 'hěn', en: 'very', pos: 'adv' },
      { zh: '太', pinyin: 'tài', en: 'too / extremely', pos: 'adv' },
      { zh: '都', pinyin: 'dōu', en: 'all / both', pos: 'adv' },
      { zh: '也', pinyin: 'yě', en: 'also / too', pos: 'adv' },
      { zh: '高兴', pinyin: 'gāo xìng', en: 'happy / glad', pos: 'adj' },
      { zh: '漂亮', pinyin: 'piào liang', en: 'pretty / beautiful', pos: 'adj' },
      { zh: '热', pinyin: 'rè', en: 'hot', pos: 'adj' },
      { zh: '冷', pinyin: 'lěng', en: 'cold', pos: 'adj' },
      { zh: '喜欢', pinyin: 'xǐ huan', en: 'to like', pos: 'v' },
      { zh: '想', pinyin: 'xiǎng', en: 'to want / to think / to miss', pos: 'v' },
    ],
    9: [
      // Question words and sentence tools
      { zh: '什么', pinyin: 'shén me', en: 'what', pos: 'pron' },
      { zh: '哪', pinyin: 'nǎ', en: 'which', pos: 'pron' },
      { zh: '哪儿', pinyin: 'nǎr', en: 'where', pos: 'pron' },
      { zh: '怎么', pinyin: 'zěn me', en: 'how / why', pos: 'pron' },
      { zh: '怎么样', pinyin: 'zěn me yàng', en: "how about? / what's it like?", pos: 'pron' },
      { zh: '为什么', pinyin: 'wèi shén me', en: 'why', pos: 'pron' },
      { zh: '了', pinyin: 'le', en: 'completion / change of state particle', pos: 'part' },
      { zh: '呢', pinyin: 'ne', en: "and you? / what about? (tag particle)", pos: 'part' },
      { zh: '能', pinyin: 'néng', en: 'can / to be able to', pos: 'v' },
      { zh: '会', pinyin: 'huì', en: 'can / know how to / will', pos: 'v' },
      { zh: '打电话', pinyin: 'dǎ diàn huà', en: 'to make a phone call', pos: 'v' },
      { zh: '电话', pinyin: 'diàn huà', en: 'telephone', pos: 'n' },
      { zh: '那', pinyin: 'nà', en: 'that', pos: 'pron' },
      { zh: '这', pinyin: 'zhè', en: 'this', pos: 'pron' },
      { zh: '些', pinyin: 'xiē', en: 'some / a few (measure word)', pos: 'mw' },
    ],
    10: [
      // Everyday nouns and connecting words
      { zh: '书', pinyin: 'shū', en: 'book', pos: 'n' },
      { zh: '衣服', pinyin: 'yī fu', en: 'clothes / clothing', pos: 'n' },
      { zh: '桌子', pinyin: 'zhuō zi', en: 'table / desk', pos: 'n' },
      { zh: '椅子', pinyin: 'yǐ zi', en: 'chair', pos: 'n' },
      { zh: '电脑', pinyin: 'diàn nǎo', en: 'computer', pos: 'n' },
      { zh: '电视', pinyin: 'diàn shì', en: 'television', pos: 'n' },
      { zh: '电影', pinyin: 'diàn yǐng', en: 'movie / film', pos: 'n' },
      { zh: '猫', pinyin: 'māo', en: 'cat', pos: 'n' },
      { zh: '狗', pinyin: 'gǒu', en: 'dog', pos: 'n' },
      { zh: '汉语', pinyin: 'Hàn yǔ', en: 'Chinese language (Mandarin)', pos: 'n' },
      { zh: '字', pinyin: 'zì', en: 'character / word', pos: 'n' },
      { zh: '和', pinyin: 'hé', en: 'and / with', pos: 'conj' },
      { zh: '但是', pinyin: 'dàn shì', en: 'but / however', pos: 'conj' },
      { zh: '因为', pinyin: 'yīn wèi', en: 'because', pos: 'conj' },
      { zh: '所以', pinyin: 'suǒ yǐ', en: 'so / therefore', pos: 'conj' },
    ],
  },

  // ─────────────────────────────────────────────
  // A2  (HSK 2 — everyday communication)
  // ─────────────────────────────────────────────
  A2: {
    1: [
      // Daily routines
      { zh: '起床', pinyin: 'qǐ chuáng', en: 'to get up / to get out of bed', pos: 'v' },
      { zh: '洗澡', pinyin: 'xǐ zǎo', en: 'to take a shower / to bathe', pos: 'v' },
      { zh: '刷牙', pinyin: 'shuā yá', en: 'to brush teeth', pos: 'v' },
      { zh: '穿', pinyin: 'chuān', en: 'to wear / to put on (clothing)', pos: 'v' },
      { zh: '出发', pinyin: 'chū fā', en: 'to set off / to depart', pos: 'v' },
      { zh: '上班', pinyin: 'shàng bān', en: 'to go to work', pos: 'v' },
      { zh: '下班', pinyin: 'xià bān', en: 'to finish work / to get off work', pos: 'v' },
      { zh: '做饭', pinyin: 'zuò fàn', en: 'to cook / to make a meal', pos: 'v' },
      { zh: '休息', pinyin: 'xiū xi', en: 'to rest', pos: 'v' },
      { zh: '锻炼', pinyin: 'duàn liàn', en: 'to exercise / to work out', pos: 'v' },
      { zh: '早上', pinyin: 'zǎo shang', en: 'morning (early)', pos: 'n' },
      { zh: '晚上', pinyin: 'wǎn shang', en: 'evening / night', pos: 'n' },
      { zh: '每天', pinyin: 'měi tiān', en: 'every day', pos: 'n' },
      { zh: '以前', pinyin: 'yǐ qián', en: 'before / in the past', pos: 'n/adv' },
      { zh: '以后', pinyin: 'yǐ hòu', en: 'after / in the future', pos: 'n/adv' },
    ],
    2: [
      // Shopping and money
      { zh: '超市', pinyin: 'chāo shì', en: 'supermarket', pos: 'n' },
      { zh: '市场', pinyin: 'shì chǎng', en: 'market', pos: 'n' },
      { zh: '价格', pinyin: 'jià gé', en: 'price', pos: 'n' },
      { zh: '便宜', pinyin: 'pián yi', en: 'cheap / inexpensive', pos: 'adj' },
      { zh: '贵', pinyin: 'guì', en: 'expensive', pos: 'adj' },
      { zh: '付钱', pinyin: 'fù qián', en: 'to pay money', pos: 'v' },
      { zh: '找钱', pinyin: 'zhǎo qián', en: 'to give change', pos: 'v' },
      { zh: '块', pinyin: 'kuài', en: 'yuan (spoken, informal)', pos: 'mw' },
      { zh: '元', pinyin: 'yuán', en: 'yuan (written, formal)', pos: 'mw' },
      { zh: '需要', pinyin: 'xū yào', en: 'to need', pos: 'v' },
      { zh: '帮助', pinyin: 'bāng zhù', en: 'to help / help (n)', pos: 'v/n' },
      { zh: '卖', pinyin: 'mài', en: 'to sell', pos: 'v' },
      { zh: '件', pinyin: 'jiàn', en: 'measure word for clothing/items', pos: 'mw' },
      { zh: '条', pinyin: 'tiáo', en: 'measure word for long/thin items', pos: 'mw' },
      { zh: '双', pinyin: 'shuāng', en: 'pair / measure word for pairs', pos: 'mw' },
    ],
    3: [
      // Body and health
      { zh: '头', pinyin: 'tóu', en: 'head', pos: 'n' },
      { zh: '眼睛', pinyin: 'yǎn jing', en: 'eye(s)', pos: 'n' },
      { zh: '嘴', pinyin: 'zuǐ', en: 'mouth', pos: 'n' },
      { zh: '手', pinyin: 'shǒu', en: 'hand', pos: 'n' },
      { zh: '脚', pinyin: 'jiǎo', en: 'foot / leg (lower)', pos: 'n' },
      { zh: '身体', pinyin: 'shēn tǐ', en: 'body / health', pos: 'n' },
      { zh: '生病', pinyin: 'shēng bìng', en: 'to get sick / to fall ill', pos: 'v' },
      { zh: '医生', pinyin: 'yī shēng', en: 'doctor', pos: 'n' },
      { zh: '药', pinyin: 'yào', en: 'medicine / drug', pos: 'n' },
      { zh: '疼', pinyin: 'téng', en: 'to hurt / to ache / painful', pos: 'v/adj' },
      { zh: '发烧', pinyin: 'fā shāo', en: 'to have a fever', pos: 'v' },
      { zh: '感冒', pinyin: 'gǎn mào', en: 'to have a cold / common cold', pos: 'v/n' },
      { zh: '健康', pinyin: 'jiàn kāng', en: 'healthy / health', pos: 'adj/n' },
      { zh: '累', pinyin: 'lèi', en: 'tired', pos: 'adj' },
      { zh: '舒服', pinyin: 'shū fu', en: 'comfortable / to feel well', pos: 'adj' },
    ],
    4: [
      // Weather and seasons
      { zh: '天气', pinyin: 'tiān qì', en: 'weather', pos: 'n' },
      { zh: '下雨', pinyin: 'xià yǔ', en: 'to rain', pos: 'v' },
      { zh: '下雪', pinyin: 'xià xuě', en: 'to snow', pos: 'v' },
      { zh: '刮风', pinyin: 'guā fēng', en: 'to be windy', pos: 'v' },
      { zh: '晴天', pinyin: 'qíng tiān', en: 'sunny day / clear sky', pos: 'n' },
      { zh: '阴天', pinyin: 'yīn tiān', en: 'cloudy day / overcast', pos: 'n' },
      { zh: '春天', pinyin: 'chūn tiān', en: 'spring (season)', pos: 'n' },
      { zh: '夏天', pinyin: 'xià tiān', en: 'summer', pos: 'n' },
      { zh: '秋天', pinyin: 'qiū tiān', en: 'autumn / fall', pos: 'n' },
      { zh: '冬天', pinyin: 'dōng tiān', en: 'winter', pos: 'n' },
      { zh: '温度', pinyin: 'wēn dù', en: 'temperature', pos: 'n' },
      { zh: '度', pinyin: 'dù', en: 'degree (temperature/angle)', pos: 'mw' },
      { zh: '风', pinyin: 'fēng', en: 'wind', pos: 'n' },
      { zh: '雨', pinyin: 'yǔ', en: 'rain', pos: 'n' },
      { zh: '雪', pinyin: 'xuě', en: 'snow', pos: 'n' },
    ],
    5: [
      // Hobbies and free time
      { zh: '爱好', pinyin: 'ài hào', en: 'hobby / interest', pos: 'n' },
      { zh: '运动', pinyin: 'yùn dòng', en: 'sport / exercise / to exercise', pos: 'n/v' },
      { zh: '音乐', pinyin: 'yīn yuè', en: 'music', pos: 'n' },
      { zh: '唱歌', pinyin: 'chàng gē', en: 'to sing', pos: 'v' },
      { zh: '跳舞', pinyin: 'tiào wǔ', en: 'to dance', pos: 'v' },
      { zh: '画画', pinyin: 'huà huà', en: 'to draw / to paint', pos: 'v' },
      { zh: '游泳', pinyin: 'yóu yǒng', en: 'to swim', pos: 'v' },
      { zh: '踢足球', pinyin: 'tī zú qiú', en: 'to play football / soccer', pos: 'v' },
      { zh: '打篮球', pinyin: 'dǎ lán qiú', en: 'to play basketball', pos: 'v' },
      { zh: '旅游', pinyin: 'lǚ yóu', en: 'to travel / tourism', pos: 'v/n' },
      { zh: '照相', pinyin: 'zhào xiàng', en: 'to take a photo', pos: 'v' },
      { zh: '玩', pinyin: 'wán', en: 'to play / to have fun', pos: 'v' },
      { zh: '有意思', pinyin: 'yǒu yì si', en: 'interesting / fun', pos: 'adj' },
      { zh: '有趣', pinyin: 'yǒu qù', en: 'interesting / fascinating', pos: 'adj' },
      { zh: '无聊', pinyin: 'wú liáo', en: 'boring / bored', pos: 'adj' },
    ],
    6: [
      // School and study
      { zh: '教室', pinyin: 'jiào shì', en: 'classroom', pos: 'n' },
      { zh: '作业', pinyin: 'zuò yè', en: 'homework / assignment', pos: 'n' },
      { zh: '考试', pinyin: 'kǎo shì', en: 'exam / to take an exam', pos: 'n/v' },
      { zh: '成绩', pinyin: 'chéng jì', en: 'result / grade / score', pos: 'n' },
      { zh: '复习', pinyin: 'fù xí', en: 'to revise / to review', pos: 'v' },
      { zh: '预习', pinyin: 'yù xí', en: 'to prepare (a lesson)', pos: 'v' },
      { zh: '笔', pinyin: 'bǐ', en: 'pen / pencil (general)', pos: 'n' },
      { zh: '本子', pinyin: 'běn zi', en: 'notebook / exercise book', pos: 'n' },
      { zh: '词典', pinyin: 'cí diǎn', en: 'dictionary', pos: 'n' },
      { zh: '年级', pinyin: 'nián jí', en: 'grade / year (school)', pos: 'n' },
      { zh: '班', pinyin: 'bān', en: 'class (school) / shift', pos: 'n' },
      { zh: '图书馆', pinyin: 'tú shū guǎn', en: 'library', pos: 'n' },
      { zh: '努力', pinyin: 'nǔ lì', en: 'hardworking / to work hard', pos: 'adj/v' },
      { zh: '认真', pinyin: 'rèn zhēn', en: 'careful / serious / conscientious', pos: 'adj' },
      { zh: '进步', pinyin: 'jìn bù', en: 'progress / to improve', pos: 'n/v' },
    ],
    7: [
      // Getting around / directions
      { zh: '路', pinyin: 'lù', en: 'road / path / route', pos: 'n' },
      { zh: '街', pinyin: 'jiē', en: 'street', pos: 'n' },
      { zh: '地铁', pinyin: 'dì tiě', en: 'subway / metro', pos: 'n' },
      { zh: '公共汽车', pinyin: 'gōng gòng qì chē', en: 'bus', pos: 'n' },
      { zh: '自行车', pinyin: 'zì xíng chē', en: 'bicycle', pos: 'n' },
      { zh: '左', pinyin: 'zuǒ', en: 'left', pos: 'n/adj' },
      { zh: '右', pinyin: 'yòu', en: 'right', pos: 'n/adj' },
      { zh: '直走', pinyin: 'zhí zǒu', en: 'go straight', pos: 'v' },
      { zh: '拐', pinyin: 'guǎi', en: 'to turn', pos: 'v' },
      { zh: '远', pinyin: 'yuǎn', en: 'far / distant', pos: 'adj' },
      { zh: '近', pinyin: 'jìn', en: 'near / close', pos: 'adj' },
      { zh: '旁边', pinyin: 'páng biān', en: 'beside / next to', pos: 'n' },
      { zh: '对面', pinyin: 'duì miàn', en: 'opposite side / across from', pos: 'n' },
      { zh: '地方', pinyin: 'dì fāng', en: 'place / area', pos: 'n' },
      { zh: '迷路', pinyin: 'mí lù', en: 'to get lost', pos: 'v' },
    ],
    8: [
      // Descriptive adjectives (expanding range)
      { zh: '高', pinyin: 'gāo', en: 'tall / high', pos: 'adj' },
      { zh: '矮', pinyin: 'ǎi', en: 'short (height)', pos: 'adj' },
      { zh: '长', pinyin: 'cháng', en: 'long', pos: 'adj' },
      { zh: '短', pinyin: 'duǎn', en: 'short (length)', pos: 'adj' },
      { zh: '新', pinyin: 'xīn', en: 'new', pos: 'adj' },
      { zh: '旧', pinyin: 'jiù', en: 'old / used', pos: 'adj' },
      { zh: '快', pinyin: 'kuài', en: 'fast / quick', pos: 'adj' },
      { zh: '慢', pinyin: 'màn', en: 'slow', pos: 'adj' },
      { zh: '容易', pinyin: 'róng yì', en: 'easy', pos: 'adj' },
      { zh: '难', pinyin: 'nán', en: 'difficult / hard', pos: 'adj' },
      { zh: '干净', pinyin: 'gān jìng', en: 'clean / tidy', pos: 'adj' },
      { zh: '脏', pinyin: 'zāng', en: 'dirty', pos: 'adj' },
      { zh: '重要', pinyin: 'zhòng yào', en: 'important', pos: 'adj' },
      { zh: '有名', pinyin: 'yǒu míng', en: 'famous / well-known', pos: 'adj' },
      { zh: '可爱', pinyin: 'kě ài', en: 'cute / adorable', pos: 'adj' },
    ],
    9: [
      // More useful verbs
      { zh: '等', pinyin: 'děng', en: 'to wait', pos: 'v' },
      { zh: '找', pinyin: 'zhǎo', en: 'to look for / to find', pos: 'v' },
      { zh: '带', pinyin: 'dài', en: 'to bring / to take along', pos: 'v' },
      { zh: '借', pinyin: 'jiè', en: 'to borrow / to lend', pos: 'v' },
      { zh: '还', pinyin: 'huán', en: 'to return (something)', pos: 'v' },
      { zh: '送', pinyin: 'sòng', en: 'to give (a gift) / to send / to see off', pos: 'v' },
      { zh: '接', pinyin: 'jiē', en: 'to pick up (a person) / to receive', pos: 'v' },
      { zh: '告诉', pinyin: 'gào su', en: 'to tell', pos: 'v' },
      { zh: '问', pinyin: 'wèn', en: 'to ask (a question)', pos: 'v' },
      { zh: '回答', pinyin: 'huí dá', en: 'to answer / answer (n)', pos: 'v/n' },
      { zh: '决定', pinyin: 'jué dìng', en: 'to decide / decision', pos: 'v/n' },
      { zh: '开始', pinyin: 'kāi shǐ', en: 'to begin / to start', pos: 'v' },
      { zh: '结束', pinyin: 'jié shù', en: 'to end / to finish', pos: 'v' },
      { zh: '准备', pinyin: 'zhǔn bèi', en: 'to prepare / to get ready', pos: 'v' },
      { zh: '完成', pinyin: 'wán chéng', en: 'to complete / to finish', pos: 'v' },
    ],
    10: [
      // Time expressions and frequency
      { zh: '常常', pinyin: 'cháng cháng', en: 'often / frequently', pos: 'adv' },
      { zh: '有时候', pinyin: 'yǒu shí hou', en: 'sometimes', pos: 'adv' },
      { zh: '一起', pinyin: 'yī qǐ', en: 'together', pos: 'adv' },
      { zh: '已经', pinyin: 'yǐ jīng', en: 'already', pos: 'adv' },
      { zh: '还', pinyin: 'hái', en: 'still / also / even more', pos: 'adv' },
      { zh: '再', pinyin: 'zài', en: 'again / once more', pos: 'adv' },
      { zh: '先', pinyin: 'xiān', en: 'first / earlier', pos: 'adv' },
      { zh: '然后', pinyin: 'rán hòu', en: 'then / after that', pos: 'conj' },
      { zh: '最近', pinyin: 'zuì jìn', en: 'recently / lately', pos: 'adv' },
      { zh: '下次', pinyin: 'xià cì', en: 'next time', pos: 'n' },
      { zh: '上次', pinyin: 'shàng cì', en: 'last time', pos: 'n' },
      { zh: '一共', pinyin: 'yī gòng', en: 'in total / altogether', pos: 'adv' },
      { zh: '差不多', pinyin: 'chà bu duō', en: 'almost / about the same', pos: 'adv' },
      { zh: '一直', pinyin: 'yī zhí', en: 'straight / always / continuously', pos: 'adv' },
      { zh: '终于', pinyin: 'zhōng yú', en: 'finally / at last', pos: 'adv' },
    ],
  },

  // ─────────────────────────────────────────────
  // B1  (HSK 3–4 — independent communication)
  // ─────────────────────────────────────────────
  B1: {
    1: [
      // Emotions and opinions
      { zh: '担心', pinyin: 'dān xīn', en: 'to worry / worried', pos: 'v/adj' },
      { zh: '生气', pinyin: 'shēng qì', en: 'to be angry', pos: 'v' },
      { zh: '难过', pinyin: 'nán guò', en: 'sad / upset', pos: 'adj' },
      { zh: '兴奋', pinyin: 'xīng fèn', en: 'excited', pos: 'adj' },
      { zh: '紧张', pinyin: 'jǐn zhāng', en: 'nervous / tense', pos: 'adj' },
      { zh: '放松', pinyin: 'fàng sōng', en: 'to relax / relaxed', pos: 'v/adj' },
      { zh: '满意', pinyin: 'mǎn yì', en: 'satisfied / content', pos: 'adj' },
      { zh: '失望', pinyin: 'shī wàng', en: 'disappointed', pos: 'adj' },
      { zh: '希望', pinyin: 'xī wàng', en: 'to hope / hope (n)', pos: 'v/n' },
      { zh: '感觉', pinyin: 'gǎn jué', en: 'to feel / feeling', pos: 'v/n' },
      { zh: '认为', pinyin: 'rèn wéi', en: 'to think / to believe (opinion)', pos: 'v' },
      { zh: '觉得', pinyin: 'jué de', en: 'to feel / to think', pos: 'v' },
      { zh: '同意', pinyin: 'tóng yì', en: 'to agree', pos: 'v' },
      { zh: '反对', pinyin: 'fǎn duì', en: 'to oppose / to object', pos: 'v' },
      { zh: '理解', pinyin: 'lǐ jiě', en: 'to understand / to comprehend', pos: 'v' },
    ],
    2: [
      // Travel and places
      { zh: '旅行', pinyin: 'lǚ xíng', en: 'to travel / trip', pos: 'v/n' },
      { zh: '景色', pinyin: 'jǐng sè', en: 'scenery / landscape', pos: 'n' },
      { zh: '宾馆', pinyin: 'bīn guǎn', en: 'hotel / guesthouse', pos: 'n' },
      { zh: '地图', pinyin: 'dì tú', en: 'map', pos: 'n' },
      { zh: '护照', pinyin: 'hù zhào', en: 'passport', pos: 'n' },
      { zh: '签证', pinyin: 'qiān zhèng', en: 'visa', pos: 'n' },
      { zh: '行李', pinyin: 'xíng li', en: 'luggage / baggage', pos: 'n' },
      { zh: '订', pinyin: 'dìng', en: 'to book / to reserve', pos: 'v' },
      { zh: '取消', pinyin: 'qǔ xiāo', en: 'to cancel', pos: 'v' },
      { zh: '景点', pinyin: 'jǐng diǎn', en: 'tourist attraction / scenic spot', pos: 'n' },
      { zh: '故宫', pinyin: 'Gù Gōng', en: 'the Forbidden City', pos: 'n' },
      { zh: '长城', pinyin: 'Cháng Chéng', en: 'the Great Wall', pos: 'n' },
      { zh: '参观', pinyin: 'cān guān', en: 'to visit (a place / exhibition)', pos: 'v' },
      { zh: '游览', pinyin: 'yóu lǎn', en: 'to tour / to go sightseeing', pos: 'v' },
      { zh: '拍照', pinyin: 'pāi zhào', en: 'to take a photo', pos: 'v' },
    ],
    3: [
      // Relationships and social life
      { zh: '关系', pinyin: 'guān xi', en: 'relationship / connection', pos: 'n' },
      { zh: '结婚', pinyin: 'jié hūn', en: 'to get married', pos: 'v' },
      { zh: '离婚', pinyin: 'lí hūn', en: 'to divorce', pos: 'v' },
      { zh: '恋爱', pinyin: 'liàn ài', en: 'to be in love / romance', pos: 'v/n' },
      { zh: '邻居', pinyin: 'lín jū', en: 'neighbour', pos: 'n' },
      { zh: '互相', pinyin: 'hù xiāng', en: 'each other / mutually', pos: 'adv' },
      { zh: '支持', pinyin: 'zhī chí', en: 'to support', pos: 'v' },
      { zh: '帮忙', pinyin: 'bāng máng', en: 'to help out / to do a favour', pos: 'v' },
      { zh: '约', pinyin: 'yuē', en: 'to make an appointment / to arrange', pos: 'v' },
      { zh: '聚会', pinyin: 'jù huì', en: 'get-together / party', pos: 'n' },
      { zh: '邀请', pinyin: 'yāo qǐng', en: 'to invite / invitation', pos: 'v/n' },
      { zh: '礼物', pinyin: 'lǐ wù', en: 'gift / present', pos: 'n' },
      { zh: '祝贺', pinyin: 'zhù hè', en: 'to congratulate', pos: 'v' },
      { zh: '庆祝', pinyin: 'qìng zhù', en: 'to celebrate', pos: 'v' },
      { zh: '生日', pinyin: 'shēng rì', en: 'birthday', pos: 'n' },
    ],
    4: [
      // Food culture (intermediate)
      { zh: '口味', pinyin: 'kǒu wèi', en: 'taste / flavour preference', pos: 'n' },
      { zh: '辣', pinyin: 'là', en: 'spicy / hot', pos: 'adj' },
      { zh: '甜', pinyin: 'tián', en: 'sweet', pos: 'adj' },
      { zh: '酸', pinyin: 'suān', en: 'sour', pos: 'adj' },
      { zh: '苦', pinyin: 'kǔ', en: 'bitter', pos: 'adj' },
      { zh: '咸', pinyin: 'xián', en: 'salty', pos: 'adj' },
      { zh: '清淡', pinyin: 'qīng dàn', en: 'light (food) / bland', pos: 'adj' },
      { zh: '菜单', pinyin: 'cài dān', en: 'menu', pos: 'n' },
      { zh: '点菜', pinyin: 'diǎn cài', en: 'to order food', pos: 'v' },
      { zh: '饺子', pinyin: 'jiǎo zi', en: 'dumplings', pos: 'n' },
      { zh: '包子', pinyin: 'bāo zi', en: 'steamed bun (with filling)', pos: 'n' },
      { zh: '火锅', pinyin: 'huǒ guō', en: 'hot pot', pos: 'n' },
      { zh: '营养', pinyin: 'yíng yǎng', en: 'nutrition / nourishing', pos: 'n/adj' },
      { zh: '食材', pinyin: 'shí cái', en: 'ingredient', pos: 'n' },
      { zh: '烹饪', pinyin: 'pēng rèn', en: 'cooking / culinary art', pos: 'n/v' },
    ],
    5: [
      // Work and career
      { zh: '公司', pinyin: 'gōng sī', en: 'company / firm', pos: 'n' },
      { zh: '职业', pinyin: 'zhí yè', en: 'profession / occupation', pos: 'n' },
      { zh: '经理', pinyin: 'jīng lǐ', en: 'manager', pos: 'n' },
      { zh: '同事', pinyin: 'tóng shì', en: 'colleague', pos: 'n' },
      { zh: '面试', pinyin: 'miàn shì', en: 'interview / to interview', pos: 'n/v' },
      { zh: '合同', pinyin: 'hé tong', en: 'contract', pos: 'n' },
      { zh: '薪水', pinyin: 'xīn shuǐ', en: 'salary / wages', pos: 'n' },
      { zh: '加班', pinyin: 'jiā bān', en: 'to work overtime', pos: 'v' },
      { zh: '请假', pinyin: 'qǐng jià', en: 'to ask for leave / to take time off', pos: 'v' },
      { zh: '会议', pinyin: 'huì yì', en: 'meeting / conference', pos: 'n' },
      { zh: '项目', pinyin: 'xiàng mù', en: 'project', pos: 'n' },
      { zh: '完成', pinyin: 'wán chéng', en: 'to complete / to accomplish', pos: 'v' },
      { zh: '负责', pinyin: 'fù zé', en: 'to be responsible for', pos: 'v' },
      { zh: '压力', pinyin: 'yā lì', en: 'pressure / stress', pos: 'n' },
      { zh: '成功', pinyin: 'chéng gōng', en: 'to succeed / success', pos: 'v/n' },
    ],
    6: [
      // Study and learning (intermediate)
      { zh: '专业', pinyin: 'zhuān yè', en: 'major (university) / speciality', pos: 'n' },
      { zh: '大学', pinyin: 'dà xué', en: 'university / college', pos: 'n' },
      { zh: '毕业', pinyin: 'bì yè', en: 'to graduate', pos: 'v' },
      { zh: '研究', pinyin: 'yán jiū', en: 'to research / research (n)', pos: 'v/n' },
      { zh: '讨论', pinyin: 'tǎo lùn', en: 'to discuss / discussion', pos: 'v/n' },
      { zh: '练习', pinyin: 'liàn xí', en: 'to practise / exercise (n)', pos: 'v/n' },
      { zh: '翻译', pinyin: 'fān yì', en: 'to translate / translation', pos: 'v/n' },
      { zh: '语法', pinyin: 'yǔ fǎ', en: 'grammar', pos: 'n' },
      { zh: '发音', pinyin: 'fā yīn', en: 'pronunciation', pos: 'n' },
      { zh: '词汇', pinyin: 'cí huì', en: 'vocabulary', pos: 'n' },
      { zh: '方法', pinyin: 'fāng fǎ', en: 'method / way (of doing something)', pos: 'n' },
      { zh: '解释', pinyin: 'jiě shì', en: 'to explain / explanation', pos: 'v/n' },
      { zh: '举例子', pinyin: 'jǔ lì zi', en: 'to give an example', pos: 'v' },
      { zh: '总结', pinyin: 'zǒng jié', en: 'to summarise / summary', pos: 'v/n' },
      { zh: '提高', pinyin: 'tí gāo', en: 'to improve / to raise (a level)', pos: 'v' },
    ],
    7: [
      // Nature and environment
      { zh: '自然', pinyin: 'zì rán', en: 'nature / natural', pos: 'n/adj' },
      { zh: '环境', pinyin: 'huán jìng', en: 'environment', pos: 'n' },
      { zh: '森林', pinyin: 'sēn lín', en: 'forest', pos: 'n' },
      { zh: '河流', pinyin: 'hé liú', en: 'river', pos: 'n' },
      { zh: '山', pinyin: 'shān', en: 'mountain / hill', pos: 'n' },
      { zh: '海', pinyin: 'hǎi', en: 'sea / ocean', pos: 'n' },
      { zh: '动物', pinyin: 'dòng wù', en: 'animal', pos: 'n' },
      { zh: '植物', pinyin: 'zhí wù', en: 'plant', pos: 'n' },
      { zh: '花', pinyin: 'huā', en: 'flower', pos: 'n' },
      { zh: '树', pinyin: 'shù', en: 'tree', pos: 'n' },
      { zh: '保护', pinyin: 'bǎo hù', en: 'to protect / protection', pos: 'v/n' },
      { zh: '污染', pinyin: 'wū rǎn', en: 'to pollute / pollution', pos: 'v/n' },
      { zh: '节约', pinyin: 'jié yuē', en: 'to save / to economise', pos: 'v' },
      { zh: '垃圾', pinyin: 'lā jī', en: 'rubbish / garbage', pos: 'n' },
      { zh: '气候', pinyin: 'qì hòu', en: 'climate', pos: 'n' },
    ],
    8: [
      // Technology and media
      { zh: '网络', pinyin: 'wǎng luò', en: 'internet / network', pos: 'n' },
      { zh: '手机', pinyin: 'shǒu jī', en: 'mobile phone', pos: 'n' },
      { zh: '软件', pinyin: 'ruǎn jiàn', en: 'software', pos: 'n' },
      { zh: '应用', pinyin: 'yìng yòng', en: 'app / application', pos: 'n' },
      { zh: '搜索', pinyin: 'sōu suǒ', en: 'to search', pos: 'v' },
      { zh: '下载', pinyin: 'xià zài', en: 'to download', pos: 'v' },
      { zh: '上传', pinyin: 'shàng chuán', en: 'to upload', pos: 'v' },
      { zh: '发送', pinyin: 'fā sòng', en: 'to send (message/file)', pos: 'v' },
      { zh: '信息', pinyin: 'xìn xī', en: 'information / message', pos: 'n' },
      { zh: '社交媒体', pinyin: 'shè jiāo méi tǐ', en: 'social media', pos: 'n' },
      { zh: '视频', pinyin: 'shì pín', en: 'video', pos: 'n' },
      { zh: '密码', pinyin: 'mì mǎ', en: 'password', pos: 'n' },
      { zh: '安全', pinyin: 'ān quán', en: 'safe / safety / security', pos: 'adj/n' },
      { zh: '科技', pinyin: 'kē jì', en: 'science and technology', pos: 'n' },
      { zh: '发展', pinyin: 'fā zhǎn', en: 'to develop / development', pos: 'v/n' },
    ],
    9: [
      // Abstract concepts and opinions
      { zh: '问题', pinyin: 'wèn tí', en: 'problem / question / issue', pos: 'n' },
      { zh: '原因', pinyin: 'yuán yīn', en: 'reason / cause', pos: 'n' },
      { zh: '结果', pinyin: 'jié guǒ', en: 'result / outcome', pos: 'n' },
      { zh: '影响', pinyin: 'yǐng xiǎng', en: 'to influence / influence (n)', pos: 'v/n' },
      { zh: '解决', pinyin: 'jiě jué', en: 'to solve / to resolve', pos: 'v' },
      { zh: '建议', pinyin: 'jiàn yì', en: 'to suggest / suggestion', pos: 'v/n' },
      { zh: '选择', pinyin: 'xuǎn zé', en: 'to choose / choice', pos: 'v/n' },
      { zh: '比较', pinyin: 'bǐ jiào', en: 'to compare / relatively', pos: 'v/adv' },
      { zh: '区别', pinyin: 'qū bié', en: 'difference / to differ', pos: 'n/v' },
      { zh: '观点', pinyin: 'guān diǎn', en: 'point of view / opinion', pos: 'n' },
      { zh: '态度', pinyin: 'tài du', en: 'attitude', pos: 'n' },
      { zh: '习惯', pinyin: 'xí guàn', en: 'habit / custom / to be used to', pos: 'n/v' },
      { zh: '文化', pinyin: 'wén huà', en: 'culture', pos: 'n' },
      { zh: '传统', pinyin: 'chuán tǒng', en: 'tradition / traditional', pos: 'n/adj' },
      { zh: '社会', pinyin: 'shè huì', en: 'society / social', pos: 'n/adj' },
    ],
    10: [
      // Expressing degree and nuance
      { zh: '非常', pinyin: 'fēi cháng', en: 'extremely / very much', pos: 'adv' },
      { zh: '相当', pinyin: 'xiāng dāng', en: 'quite / fairly / rather', pos: 'adv' },
      { zh: '稍微', pinyin: 'shāo wēi', en: 'slightly / a little', pos: 'adv' },
      { zh: '根本', pinyin: 'gēn běn', en: 'fundamentally / at all (in negation)', pos: 'adv' },
      { zh: '只有', pinyin: 'zhǐ yǒu', en: 'only if / only when', pos: 'conj' },
      { zh: '不仅', pinyin: 'bù jǐn', en: 'not only', pos: 'conj' },
      { zh: '而且', pinyin: 'ér qiě', en: 'and also / moreover', pos: 'conj' },
      { zh: '虽然', pinyin: 'suī rán', en: 'although / even though', pos: 'conj' },
      { zh: '如果', pinyin: 'rú guǒ', en: 'if', pos: 'conj' },
      { zh: '即使', pinyin: 'jí shǐ', en: 'even if', pos: 'conj' },
      { zh: '只要', pinyin: 'zhǐ yào', en: 'as long as / provided that', pos: 'conj' },
      { zh: '无论', pinyin: 'wú lùn', en: 'no matter (what/how)', pos: 'conj' },
      { zh: '一方面', pinyin: 'yī fāng miàn', en: 'on one hand', pos: 'conj' },
      { zh: '另一方面', pinyin: 'lìng yī fāng miàn', en: 'on the other hand', pos: 'conj' },
      { zh: '总的来说', pinyin: 'zǒng de lái shuō', en: 'generally speaking', pos: 'adv' },
    ],
  },

  // ─────────────────────────────────────────────
  // B2  (HSK 4–5 — fluent everyday use)
  // ─────────────────────────────────────────────
  B2: {
    1: [
      // Current affairs and society
      { zh: '经济', pinyin: 'jīng jì', en: 'economy / economic', pos: 'n/adj' },
      { zh: '政治', pinyin: 'zhèng zhì', en: 'politics / political', pos: 'n/adj' },
      { zh: '政府', pinyin: 'zhèng fǔ', en: 'government', pos: 'n' },
      { zh: '法律', pinyin: 'fǎ lǜ', en: 'law / legal', pos: 'n/adj' },
      { zh: '权利', pinyin: 'quán lì', en: 'right / rights', pos: 'n' },
      { zh: '责任', pinyin: 'zé rèn', en: 'responsibility / duty', pos: 'n' },
      { zh: '新闻', pinyin: 'xīn wén', en: 'news', pos: 'n' },
      { zh: '报道', pinyin: 'bào dào', en: 'to report / news report', pos: 'v/n' },
      { zh: '舆论', pinyin: 'yú lùn', en: 'public opinion', pos: 'n' },
      { zh: '争议', pinyin: 'zhēng yì', en: 'controversy / dispute', pos: 'n' },
      { zh: '改革', pinyin: 'gǎi gé', en: 'reform / to reform', pos: 'n/v' },
      { zh: '措施', pinyin: 'cuò shī', en: 'measure / step (action taken)', pos: 'n' },
      { zh: '促进', pinyin: 'cù jìn', en: 'to promote / to facilitate', pos: 'v' },
      { zh: '实现', pinyin: 'shí xiàn', en: 'to realise / to achieve', pos: 'v' },
      { zh: '目标', pinyin: 'mù biāo', en: 'goal / target / objective', pos: 'n' },
    ],
    2: [
      // Finance and business
      { zh: '投资', pinyin: 'tóu zī', en: 'to invest / investment', pos: 'v/n' },
      { zh: '利润', pinyin: 'lì rùn', en: 'profit', pos: 'n' },
      { zh: '消费', pinyin: 'xiāo fèi', en: 'to consume / consumption', pos: 'v/n' },
      { zh: '市场', pinyin: 'shì chǎng', en: 'market', pos: 'n' },
      { zh: '竞争', pinyin: 'jìng zhēng', en: 'competition / to compete', pos: 'n/v' },
      { zh: '品牌', pinyin: 'pǐn pái', en: 'brand', pos: 'n' },
      { zh: '策略', pinyin: 'cè lüè', en: 'strategy', pos: 'n' },
      { zh: '合作', pinyin: 'hé zuò', en: 'to cooperate / cooperation', pos: 'v/n' },
      { zh: '谈判', pinyin: 'tán pàn', en: 'to negotiate / negotiation', pos: 'v/n' },
      { zh: '协议', pinyin: 'xié yì', en: 'agreement / protocol', pos: 'n' },
      { zh: '资金', pinyin: 'zī jīn', en: 'funds / capital', pos: 'n' },
      { zh: '预算', pinyin: 'yù suàn', en: 'budget', pos: 'n' },
      { zh: '成本', pinyin: 'chéng běn', en: 'cost', pos: 'n' },
      { zh: '效益', pinyin: 'xiào yì', en: 'benefit / efficiency', pos: 'n' },
      { zh: '风险', pinyin: 'fēng xiǎn', en: 'risk', pos: 'n' },
    ],
    3: [
      // Education (advanced)
      { zh: '素质', pinyin: 'sù zhì', en: 'quality / character (personal)', pos: 'n' },
      { zh: '培养', pinyin: 'péi yǎng', en: 'to cultivate / to train / to raise', pos: 'v' },
      { zh: '能力', pinyin: 'néng lì', en: 'ability / capability', pos: 'n' },
      { zh: '创造力', pinyin: 'chuàng zào lì', en: 'creativity', pos: 'n' },
      { zh: '批判性思维', pinyin: 'pī pàn xìng sī wéi', en: 'critical thinking', pos: 'n' },
      { zh: '课程', pinyin: 'kè chéng', en: 'curriculum / course', pos: 'n' },
      { zh: '奖学金', pinyin: 'jiǎng xué jīn', en: 'scholarship', pos: 'n' },
      { zh: '论文', pinyin: 'lùn wén', en: 'thesis / dissertation / paper', pos: 'n' },
      { zh: '导师', pinyin: 'dǎo shī', en: 'supervisor / mentor', pos: 'n' },
      { zh: '实习', pinyin: 'shí xí', en: 'internship / to intern', pos: 'n/v' },
      { zh: '竞赛', pinyin: 'jìng sài', en: 'competition / contest', pos: 'n' },
      { zh: '资源', pinyin: 'zī yuán', en: 'resource', pos: 'n' },
      { zh: '启发', pinyin: 'qǐ fā', en: 'to inspire / to enlighten', pos: 'v' },
      { zh: '积累', pinyin: 'jī lěi', en: 'to accumulate / accumulation', pos: 'v/n' },
      { zh: '终身学习', pinyin: 'zhōng shēn xué xí', en: 'lifelong learning', pos: 'n' },
    ],
    4: [
      // Health and medicine (advanced)
      { zh: '症状', pinyin: 'zhèng zhuàng', en: 'symptom', pos: 'n' },
      { zh: '治疗', pinyin: 'zhì liáo', en: 'treatment / to treat', pos: 'n/v' },
      { zh: '手术', pinyin: 'shǒu shù', en: 'operation / surgery', pos: 'n' },
      { zh: '预防', pinyin: 'yù fáng', en: 'to prevent / prevention', pos: 'v/n' },
      { zh: '免疫', pinyin: 'miǎn yì', en: 'immunity / immune', pos: 'n/adj' },
      { zh: '疫苗', pinyin: 'yì miáo', en: 'vaccine', pos: 'n' },
      { zh: '慢性病', pinyin: 'màn xìng bìng', en: 'chronic disease', pos: 'n' },
      { zh: '心理', pinyin: 'xīn lǐ', en: 'psychology / mental', pos: 'n/adj' },
      { zh: '压力', pinyin: 'yā lì', en: 'stress / pressure', pos: 'n' },
      { zh: '焦虑', pinyin: 'jiāo lǜ', en: 'anxiety / anxious', pos: 'n/adj' },
      { zh: '抑郁', pinyin: 'yì yù', en: 'depression / depressed', pos: 'n/adj' },
      { zh: '均衡', pinyin: 'jūn héng', en: 'balanced / well-balanced', pos: 'adj' },
      { zh: '饮食', pinyin: 'yǐn shí', en: 'diet / food and drink', pos: 'n' },
      { zh: '恢复', pinyin: 'huī fù', en: 'to recover / recovery', pos: 'v/n' },
      { zh: '急救', pinyin: 'jí jiù', en: 'first aid / emergency rescue', pos: 'n' },
    ],
    5: [
      // Environment and sustainability
      { zh: '可持续', pinyin: 'kě chí xù', en: 'sustainable', pos: 'adj' },
      { zh: '碳排放', pinyin: 'tàn pái fàng', en: 'carbon emissions', pos: 'n' },
      { zh: '全球变暖', pinyin: 'quán qiú biàn nuǎn', en: 'global warming', pos: 'n' },
      { zh: '可再生能源', pinyin: 'kě zài shēng néng yuán', en: 'renewable energy', pos: 'n' },
      { zh: '生态系统', pinyin: 'shēng tài xì tǒng', en: 'ecosystem', pos: 'n' },
      { zh: '濒危', pinyin: 'bīn wēi', en: 'endangered', pos: 'adj' },
      { zh: '物种', pinyin: 'wù zhǒng', en: 'species', pos: 'n' },
      { zh: '回收', pinyin: 'huí shōu', en: 'to recycle / recycling', pos: 'v/n' },
      { zh: '排放', pinyin: 'pái fàng', en: 'to emit / emissions', pos: 'v/n' },
      { zh: '绿色', pinyin: 'lǜ sè', en: 'green / eco-friendly', pos: 'adj' },
      { zh: '节能', pinyin: 'jié néng', en: 'energy-saving', pos: 'adj' },
      { zh: '自然灾害', pinyin: 'zì rán zāi hài', en: 'natural disaster', pos: 'n' },
      { zh: '洪水', pinyin: 'hóng shuǐ', en: 'flood', pos: 'n' },
      { zh: '干旱', pinyin: 'gān hàn', en: 'drought', pos: 'n' },
      { zh: '意识', pinyin: 'yì shí', en: 'awareness / consciousness', pos: 'n' },
    ],
    6: [
      // Art and culture
      { zh: '艺术', pinyin: 'yì shù', en: 'art', pos: 'n' },
      { zh: '文学', pinyin: 'wén xué', en: 'literature', pos: 'n' },
      { zh: '建筑', pinyin: 'jiàn zhù', en: 'architecture / building', pos: 'n' },
      { zh: '博物馆', pinyin: 'bó wù guǎn', en: 'museum', pos: 'n' },
      { zh: '展览', pinyin: 'zhǎn lǎn', en: 'exhibition', pos: 'n' },
      { zh: '遗产', pinyin: 'yí chǎn', en: 'heritage / legacy', pos: 'n' },
      { zh: '民俗', pinyin: 'mín sú', en: 'folk customs', pos: 'n' },
      { zh: '节日', pinyin: 'jié rì', en: 'festival / holiday', pos: 'n' },
      { zh: '习俗', pinyin: 'xí sú', en: 'custom / convention', pos: 'n' },
      { zh: '欣赏', pinyin: 'xīn shǎng', en: 'to appreciate / to enjoy', pos: 'v' },
      { zh: '创作', pinyin: 'chuàng zuò', en: 'to create / creative work', pos: 'v/n' },
      { zh: '风格', pinyin: 'fēng gé', en: 'style', pos: 'n' },
      { zh: '象征', pinyin: 'xiàng zhēng', en: 'to symbolise / symbol', pos: 'v/n' },
      { zh: '影响深远', pinyin: 'yǐng xiǎng shēn yuǎn', en: 'far-reaching influence', pos: 'adj' },
      { zh: '保留', pinyin: 'bǎo liú', en: 'to preserve / to keep', pos: 'v' },
    ],
    7: [
      // Complex mental and philosophical concepts
      { zh: '逻辑', pinyin: 'luó jí', en: 'logic / logical', pos: 'n/adj' },
      { zh: '哲学', pinyin: 'zhé xué', en: 'philosophy', pos: 'n' },
      { zh: '价值观', pinyin: 'jià zhí guān', en: 'values / value system', pos: 'n' },
      { zh: '道德', pinyin: 'dào dé', en: 'morality / ethics / moral', pos: 'n/adj' },
      { zh: '矛盾', pinyin: 'máo dùn', en: 'contradiction / conflict', pos: 'n' },
      { zh: '本质', pinyin: 'běn zhì', en: 'essence / nature (of something)', pos: 'n' },
      { zh: '抽象', pinyin: 'chōu xiàng', en: 'abstract', pos: 'adj' },
      { zh: '具体', pinyin: 'jù tǐ', en: 'concrete / specific', pos: 'adj' },
      { zh: '主观', pinyin: 'zhǔ guān', en: 'subjective', pos: 'adj' },
      { zh: '客观', pinyin: 'kè guān', en: 'objective', pos: 'adj' },
      { zh: '偏见', pinyin: 'piān jiàn', en: 'prejudice / bias', pos: 'n' },
      { zh: '平等', pinyin: 'píng děng', en: 'equality / equal', pos: 'n/adj' },
      { zh: '公平', pinyin: 'gōng píng', en: 'fair / fairness', pos: 'adj/n' },
      { zh: '歧视', pinyin: 'qí shì', en: 'to discriminate / discrimination', pos: 'v/n' },
      { zh: '包容', pinyin: 'bāo róng', en: 'tolerant / to accommodate', pos: 'adj/v' },
    ],
    8: [
      // Science and research
      { zh: '实验', pinyin: 'shí yàn', en: 'experiment / to experiment', pos: 'n/v' },
      { zh: '数据', pinyin: 'shù jù', en: 'data', pos: 'n' },
      { zh: '分析', pinyin: 'fēn xī', en: 'to analyse / analysis', pos: 'v/n' },
      { zh: '假设', pinyin: 'jiǎ shè', en: 'hypothesis / to assume', pos: 'n/v' },
      { zh: '证明', pinyin: 'zhèng míng', en: 'to prove / proof', pos: 'v/n' },
      { zh: '结论', pinyin: 'jié lùn', en: 'conclusion', pos: 'n' },
      { zh: '技术', pinyin: 'jì shù', en: 'technology / technique', pos: 'n' },
      { zh: '创新', pinyin: 'chuàng xīn', en: 'innovation / to innovate', pos: 'n/v' },
      { zh: '人工智能', pinyin: 'rén gōng zhì néng', en: 'artificial intelligence (AI)', pos: 'n' },
      { zh: '大数据', pinyin: 'dà shù jù', en: 'big data', pos: 'n' },
      { zh: '算法', pinyin: 'suàn fǎ', en: 'algorithm', pos: 'n' },
      { zh: '数字化', pinyin: 'shù zì huà', en: 'digitalisation / to digitise', pos: 'n/v' },
      { zh: '突破', pinyin: 'tū pò', en: 'breakthrough', pos: 'n' },
      { zh: '探索', pinyin: 'tàn suǒ', en: 'to explore / exploration', pos: 'v/n' },
      { zh: '应用', pinyin: 'yìng yòng', en: 'application / to apply', pos: 'n/v' },
    ],
    9: [
      // Cause, effect and reasoning
      { zh: '导致', pinyin: 'dǎo zhì', en: 'to lead to / to cause', pos: 'v' },
      { zh: '引起', pinyin: 'yǐn qǐ', en: 'to give rise to / to trigger', pos: 'v' },
      { zh: '取决于', pinyin: 'qǔ jué yú', en: 'to depend on', pos: 'v' },
      { zh: '基于', pinyin: 'jī yú', en: 'based on', pos: 'prep' },
      { zh: '针对', pinyin: 'zhēn duì', en: 'aimed at / targeting', pos: 'prep' },
      { zh: '相比', pinyin: 'xiāng bǐ', en: 'compared to / in comparison', pos: 'prep' },
      { zh: '鉴于', pinyin: 'jiàn yú', en: 'in view of / given that', pos: 'prep' },
      { zh: '从而', pinyin: 'cóng ér', en: 'thereby / so that', pos: 'conj' },
      { zh: '反而', pinyin: 'fǎn ér', en: 'on the contrary / instead', pos: 'adv' },
      { zh: '尽管', pinyin: 'jǐn guǎn', en: 'despite / although', pos: 'conj' },
      { zh: '除非', pinyin: 'chú fēi', en: 'unless', pos: 'conj' },
      { zh: '就算', pinyin: 'jiù suàn', en: 'even if / even though', pos: 'conj' },
      { zh: '不管', pinyin: 'bù guǎn', en: 'regardless of / no matter', pos: 'conj' },
      { zh: '换句话说', pinyin: 'huàn jù huà shuō', en: 'in other words', pos: 'adv' },
      { zh: '综上所述', pinyin: 'zōng shàng suǒ shù', en: 'in summary / to sum up', pos: 'adv' },
    ],
    10: [
      // Nuanced verbs and collocations
      { zh: '体现', pinyin: 'tǐ xiàn', en: 'to embody / to reflect / to manifest', pos: 'v' },
      { zh: '强调', pinyin: 'qiáng diào', en: 'to emphasise / to stress', pos: 'v' },
      { zh: '揭示', pinyin: 'jiē shì', en: 'to reveal / to expose', pos: 'v' },
      { zh: '阐述', pinyin: 'chǎn shù', en: 'to elaborate / to expound', pos: 'v' },
      { zh: '借助', pinyin: 'jiè zhù', en: 'with the help of / by means of', pos: 'prep' },
      { zh: '围绕', pinyin: 'wéi rào', en: 'around / centred on', pos: 'prep' },
      { zh: '贯穿', pinyin: 'guàn chuān', en: 'to run through / to permeate', pos: 'v' },
      { zh: '引发', pinyin: 'yǐn fā', en: 'to trigger / to spark', pos: 'v' },
      { zh: '折射', pinyin: 'zhé shè', en: 'to refract / to reflect (figuratively)', pos: 'v' },
      { zh: '呈现', pinyin: 'chéng xiàn', en: 'to present / to show', pos: 'v' },
      { zh: '涉及', pinyin: 'shè jí', en: 'to involve / to concern / to touch on', pos: 'v' },
      { zh: '局限', pinyin: 'jú xiàn', en: 'to limit / limitation', pos: 'v/n' },
      { zh: '超越', pinyin: 'chāo yuè', en: 'to transcend / to surpass', pos: 'v' },
      { zh: '融合', pinyin: 'róng hé', en: 'to merge / to blend / integration', pos: 'v/n' },
      { zh: '延伸', pinyin: 'yán shēn', en: 'to extend / to stretch', pos: 'v' },
    ],
  },

  // ─────────────────────────────────────────────
  // C1  (HSK 5–6 — proficient / near-native)
  // ─────────────────────────────────────────────
  C1: {
    1: [
      // Formal writing and rhetoric
      { zh: '论述', pinyin: 'lùn shù', en: 'to expound / discourse / argumentation', pos: 'v/n' },
      { zh: '诠释', pinyin: 'quán shì', en: 'to interpret / to annotate', pos: 'v' },
      { zh: '剖析', pinyin: 'pōu xī', en: 'to dissect / to analyse in depth', pos: 'v' },
      { zh: '驳斥', pinyin: 'bó chì', en: 'to refute / to rebut', pos: 'v' },
      { zh: '质疑', pinyin: 'zhì yí', en: 'to question / to cast doubt on', pos: 'v' },
      { zh: '印证', pinyin: 'yìn zhèng', en: 'to confirm / to corroborate', pos: 'v' },
      { zh: '援引', pinyin: 'yuán yǐn', en: 'to cite / to quote (as evidence)', pos: 'v' },
      { zh: '归纳', pinyin: 'guī nà', en: 'to generalise / inductive (reasoning)', pos: 'v' },
      { zh: '演绎', pinyin: 'yǎn yì', en: 'deduction / to deduce', pos: 'n/v' },
      { zh: '辩证', pinyin: 'biàn zhèng', en: 'dialectical', pos: 'adj' },
      { zh: '推断', pinyin: 'tuī duàn', en: 'to infer / inference', pos: 'v/n' },
      { zh: '论证', pinyin: 'lùn zhèng', en: 'to demonstrate / argumentation', pos: 'v/n' },
      { zh: '假定', pinyin: 'jiǎ dìng', en: 'to assume / assumption', pos: 'v/n' },
      { zh: '前提', pinyin: 'qián tí', en: 'premise / precondition', pos: 'n' },
      { zh: '逻辑谬误', pinyin: 'luó jí miù wù', en: 'logical fallacy', pos: 'n' },
    ],
    2: [
      // Literary and stylistic vocabulary
      { zh: '意境', pinyin: 'yì jìng', en: 'artistic conception / mood of a work', pos: 'n' },
      { zh: '意象', pinyin: 'yì xiàng', en: 'imagery (literary)', pos: 'n' },
      { zh: '隐喻', pinyin: 'yǐn yù', en: 'metaphor', pos: 'n' },
      { zh: '比喻', pinyin: 'bǐ yù', en: 'simile / metaphor / analogy', pos: 'n' },
      { zh: '讽刺', pinyin: 'fěng cì', en: 'irony / satire / to satirise', pos: 'n/v' },
      { zh: '渲染', pinyin: 'xuàn rǎn', en: 'to render / to embellish (writing)', pos: 'v' },
      { zh: '烘托', pinyin: 'hōng tuō', en: 'to set off / to highlight by contrast', pos: 'v' },
      { zh: '铺垫', pinyin: 'pū diàn', en: 'to lay the groundwork / foreshadowing', pos: 'v/n' },
      { zh: '伏笔', pinyin: 'fú bǐ', en: 'foreshadowing / hint laid earlier', pos: 'n' },
      { zh: '叙事', pinyin: 'xù shì', en: 'narration / to narrate', pos: 'n/v' },
      { zh: '笔墨', pinyin: 'bǐ mò', en: 'brush and ink / writing style', pos: 'n' },
      { zh: '韵味', pinyin: 'yùn wèi', en: 'charm / lingering appeal', pos: 'n' },
      { zh: '含蓄', pinyin: 'hán xù', en: 'implicit / reserved / understated', pos: 'adj' },
      { zh: '深刻', pinyin: 'shēn kè', en: 'profound / deep / incisive', pos: 'adj' },
      { zh: '细腻', pinyin: 'xì nì', en: 'delicate / refined / subtle', pos: 'adj' },
    ],
    3: [
      // Chengyu (4-character idioms) — Group 1
      { zh: '一举两得', pinyin: 'yī jǔ liǎng dé', en: 'kill two birds with one stone', pos: 'idiom' },
      { zh: '半途而废', pinyin: 'bàn tú ér fèi', en: 'give up halfway', pos: 'idiom' },
      { zh: '马到成功', pinyin: 'mǎ dào chéng gōng', en: 'immediate success upon arrival', pos: 'idiom' },
      { zh: '水到渠成', pinyin: 'shuǐ dào qú chéng', en: 'when conditions are right, success follows', pos: 'idiom' },
      { zh: '功亏一篑', pinyin: 'gōng kuī yī kuì', en: 'fail at the last hurdle', pos: 'idiom' },
      { zh: '持之以恒', pinyin: 'chí zhī yǐ héng', en: 'persevere consistently', pos: 'idiom' },
      { zh: '实事求是', pinyin: 'shí shì qiú shì', en: 'seek truth from facts', pos: 'idiom' },
      { zh: '触类旁通', pinyin: 'chù lèi páng tōng', en: 'grasp one and understand all related', pos: 'idiom' },
      { zh: '举一反三', pinyin: 'jǔ yī fǎn sān', en: 'draw inferences from one example', pos: 'idiom' },
      { zh: '独树一帜', pinyin: 'dú shù yī zhì', en: 'stand out uniquely / blaze one\'s own trail', pos: 'idiom' },
      { zh: '锦上添花', pinyin: 'jǐn shàng tiān huā', en: 'add splendour to what is already excellent', pos: 'idiom' },
      { zh: '雪中送炭', pinyin: 'xuě zhōng sòng tàn', en: 'send charcoal in a snowstorm (help in need)', pos: 'idiom' },
      { zh: '画龙点睛', pinyin: 'huà lóng diǎn jīng', en: "add the finishing touch / the crucial detail", pos: 'idiom' },
      { zh: '脍炙人口', pinyin: 'kuài zhì rén kǒu', en: 'widely acclaimed / on everyone\'s lips', pos: 'idiom' },
      { zh: '与时俱进', pinyin: 'yǔ shí jù jìn', en: 'keep pace with the times', pos: 'idiom' },
    ],
    4: [
      // Chengyu — Group 2 (character and society)
      { zh: '表里如一', pinyin: 'biǎo lǐ rú yī', en: 'consistent inside and out / genuine', pos: 'idiom' },
      { zh: '见微知著', pinyin: 'jiàn wēi zhī zhù', en: 'see the whole from small clues', pos: 'idiom' },
      { zh: '居安思危', pinyin: 'jū ān sī wēi', en: 'be prepared for danger in times of safety', pos: 'idiom' },
      { zh: '防微杜渐', pinyin: 'fáng wēi dù jiàn', en: 'nip problems in the bud', pos: 'idiom' },
      { zh: '大器晚成', pinyin: 'dà qì wǎn chéng', en: 'great talents mature slowly', pos: 'idiom' },
      { zh: '刻舟求剑', pinyin: 'kè zhōu qiú jiàn', en: 'take measures that no longer fit the situation', pos: 'idiom' },
      { zh: '掩耳盗铃', pinyin: 'yǎn ěr dào líng', en: 'deceive oneself / bury one\'s head in the sand', pos: 'idiom' },
      { zh: '亡羊补牢', pinyin: 'wáng yáng bǔ láo', en: 'better late than never / mend the fold after losing sheep', pos: 'idiom' },
      { zh: '因地制宜', pinyin: 'yīn dì zhì yí', en: 'adapt measures to local conditions', pos: 'idiom' },
      { zh: '兼听则明', pinyin: 'jiān tīng zé míng', en: 'listen to all sides to see clearly', pos: 'idiom' },
      { zh: '百折不挠', pinyin: 'bǎi zhé bù náo', en: 'persistent in spite of setbacks', pos: 'idiom' },
      { zh: '厚积薄发', pinyin: 'hòu jī bó fā', en: 'accumulate knowledge and apply it at the right time', pos: 'idiom' },
      { zh: '德才兼备', pinyin: 'dé cái jiān bèi', en: 'have both virtue and ability', pos: 'idiom' },
      { zh: '知行合一', pinyin: 'zhī xíng hé yī', en: 'unity of knowledge and action', pos: 'idiom' },
      { zh: '博采众长', pinyin: 'bó cǎi zhòng cháng', en: 'draw on the strengths of many', pos: 'idiom' },
    ],
    5: [
      // Advanced academic and formal register
      { zh: '范畴', pinyin: 'fàn chóu', en: 'category / domain / realm', pos: 'n' },
      { zh: '维度', pinyin: 'wéi dù', en: 'dimension / dimension of analysis', pos: 'n' },
      { zh: '框架', pinyin: 'kuàng jià', en: 'framework / structure', pos: 'n' },
      { zh: '机制', pinyin: 'jī zhì', en: 'mechanism', pos: 'n' },
      { zh: '模式', pinyin: 'mó shì', en: 'mode / pattern / model', pos: 'n' },
      { zh: '规律', pinyin: 'guī lǜ', en: 'law / rule / regularity', pos: 'n' },
      { zh: '内涵', pinyin: 'nèi hán', en: 'connotation / inner meaning', pos: 'n' },
      { zh: '外延', pinyin: 'wài yán', en: 'extension / extension of a concept', pos: 'n' },
      { zh: '层次', pinyin: 'céng cì', en: 'level / layer / hierarchy', pos: 'n' },
      { zh: '维系', pinyin: 'wéi xì', en: 'to maintain / to sustain (a relationship)', pos: 'v' },
      { zh: '制约', pinyin: 'zhì yuē', en: 'to constrain / to restrict', pos: 'v' },
      { zh: '凸显', pinyin: 'tū xiǎn', en: 'to highlight / to make prominent', pos: 'v' },
      { zh: '渗透', pinyin: 'shèn tòu', en: 'to permeate / to infiltrate', pos: 'v' },
      { zh: '契合', pinyin: 'qì hé', en: 'to be in line with / to fit perfectly', pos: 'v' },
      { zh: '彰显', pinyin: 'zhāng xiǎn', en: 'to manifest / to demonstrate clearly', pos: 'v' },
    ],
    6: [
      // Social critique and nuanced discourse
      { zh: '固化', pinyin: 'gù huà', en: 'to solidify / to become entrenched', pos: 'v' },
      { zh: '内卷', pinyin: 'nèi juǎn', en: 'involution (intense competition with diminishing returns)', pos: 'n' },
      { zh: '躺平', pinyin: 'tǎng píng', en: 'lying flat (opting out of social competition)', pos: 'v' },
      { zh: '内耗', pinyin: 'nèi hào', en: 'internal friction / emotional drain', pos: 'n' },
      { zh: '阶层', pinyin: 'jiē céng', en: 'social stratum / class', pos: 'n' },
      { zh: '流动性', pinyin: 'liú dòng xìng', en: 'mobility / fluidity', pos: 'n' },
      { zh: '话语权', pinyin: 'huà yǔ quán', en: 'right to speak / discursive power', pos: 'n' },
      { zh: '弱势群体', pinyin: 'ruò shì qún tǐ', en: 'vulnerable / marginalised groups', pos: 'n' },
      { zh: '多元化', pinyin: 'duō yuán huà', en: 'diversification / pluralism', pos: 'n' },
      { zh: '认同感', pinyin: 'rèn tóng gǎn', en: 'sense of identity / belonging', pos: 'n' },
      { zh: '共鸣', pinyin: 'gòng míng', en: 'resonance / to resonate (emotionally)', pos: 'n/v' },
      { zh: '边界感', pinyin: 'biān jiè gǎn', en: 'sense of personal boundaries', pos: 'n' },
      { zh: '网暴', pinyin: 'wǎng bào', en: 'cyberbullying / online harassment', pos: 'n' },
      { zh: '信息茧房', pinyin: 'xìn xī jiǎn fáng', en: 'information cocoon / filter bubble', pos: 'n' },
      { zh: '圈层', pinyin: 'quān céng', en: 'social bubble / interest community', pos: 'n' },
    ],
    7: [
      // Idiomatic phrases and set expressions
      { zh: '不言而喻', pinyin: 'bù yán ér yù', en: 'goes without saying / self-evident', pos: 'idiom' },
      { zh: '无可厚非', pinyin: 'wú kě hòu fēi', en: 'not to be blamed / understandable', pos: 'idiom' },
      { zh: '恰如其分', pinyin: 'qià rú qí fèn', en: 'just right / fitting and proper', pos: 'idiom' },
      { zh: '可圈可点', pinyin: 'kě quān kě diǎn', en: 'noteworthy / commendable', pos: 'idiom' },
      { zh: '难以置信', pinyin: 'nán yǐ zhì xìn', en: 'hard to believe / incredible', pos: 'idiom' },
      { zh: '不可思议', pinyin: 'bù kě sī yì', en: 'unimaginable / inconceivable', pos: 'idiom' },
      { zh: '无独有偶', pinyin: 'wú dú yǒu ǒu', en: 'not unique — there is a parallel case', pos: 'idiom' },
      { zh: '截然不同', pinyin: 'jié rán bù tóng', en: 'completely different / sharply contrasting', pos: 'idiom' },
      { zh: '不谋而合', pinyin: 'bù móu ér hé', en: 'coincide without prior consultation', pos: 'idiom' },
      { zh: '殊途同归', pinyin: 'shū tú tóng guī', en: 'different roads lead to the same destination', pos: 'idiom' },
      { zh: '百花齐放', pinyin: 'bǎi huā qí fàng', en: 'let a hundred flowers bloom / diverse flourishing', pos: 'idiom' },
      { zh: '与众不同', pinyin: 'yǔ zhòng bù tóng', en: 'different from the rest / unique', pos: 'idiom' },
      { zh: '一以贯之', pinyin: 'yī yǐ guàn zhī', en: 'consistent / running through everything', pos: 'idiom' },
      { zh: '相辅相成', pinyin: 'xiāng fǔ xiāng chéng', en: 'complement each other', pos: 'idiom' },
      { zh: '大势所趋', pinyin: 'dà shì suǒ qū', en: 'the inevitable trend / the way things are going', pos: 'idiom' },
    ],
    8: [
      // Psychology and interpersonal depth
      { zh: '潜意识', pinyin: 'qián yì shí', en: 'subconscious', pos: 'n' },
      { zh: '自我认知', pinyin: 'zì wǒ rèn zhī', en: 'self-awareness', pos: 'n' },
      { zh: '情绪管理', pinyin: 'qíng xù guǎn lǐ', en: 'emotional management / regulation', pos: 'n' },
      { zh: '共情', pinyin: 'gòng qíng', en: 'empathy / to empathise', pos: 'n/v' },
      { zh: '内驱力', pinyin: 'nèi qū lì', en: 'intrinsic motivation', pos: 'n' },
      { zh: '自律', pinyin: 'zì lǜ', en: 'self-discipline', pos: 'n' },
      { zh: '成就感', pinyin: 'chéng jiù gǎn', en: 'sense of achievement', pos: 'n' },
      { zh: '归属感', pinyin: 'guī shǔ gǎn', en: 'sense of belonging', pos: 'n' },
      { zh: '挫败感', pinyin: 'cuò bài gǎn', en: 'sense of frustration / defeatism', pos: 'n' },
      { zh: '价值感', pinyin: 'jià zhí gǎn', en: 'sense of self-worth', pos: 'n' },
      { zh: '边界', pinyin: 'biān jiè', en: 'boundary / limit', pos: 'n' },
      { zh: '执念', pinyin: 'zhí niàn', en: 'obsession / fixation', pos: 'n' },
      { zh: '释怀', pinyin: 'shì huái', en: 'to let go / to make peace with', pos: 'v' },
      { zh: '疗愈', pinyin: 'liáo yù', en: 'healing / to heal (emotionally)', pos: 'n/v' },
      { zh: '钝感力', pinyin: 'dùn gǎn lì', en: 'resilience through insensitivity / bluntness as a strength', pos: 'n' },
    ],
    9: [
      // Classical and literary allusions
      { zh: '以古鉴今', pinyin: 'yǐ gǔ jiàn jīn', en: 'use the past as a mirror for the present', pos: 'idiom' },
      { zh: '师古不泥古', pinyin: 'shī gǔ bù nì gǔ', en: 'learn from the past without being bound by it', pos: 'saying' },
      { zh: '文以载道', pinyin: 'wén yǐ zài dào', en: 'literature as a vehicle for moral truth', pos: 'saying' },
      { zh: '知行合一', pinyin: 'zhī xíng hé yī', en: 'unity of knowledge and action (Wang Yangming)', pos: 'saying' },
      { zh: '厚德载物', pinyin: 'hòu dé zài wù', en: 'great virtue supports all things', pos: 'saying' },
      { zh: '天下为公', pinyin: 'tiān xià wéi gōng', en: 'the world belongs to everyone (Confucian ideal)', pos: 'saying' },
      { zh: '民为贵', pinyin: 'mín wéi guì', en: 'the people are most important (Mencius)', pos: 'saying' },
      { zh: '路漫漫其修远兮', pinyin: 'lù màn màn qí xiū yuǎn xī', en: 'the road ahead is long and far (Qu Yuan)', pos: 'saying' },
      { zh: '兼济天下', pinyin: 'jiān jì tiān xià', en: 'to benefit all under heaven', pos: 'idiom' },
      { zh: '独善其身', pinyin: 'dú shàn qí shēn', en: 'to cultivate one\'s own virtue in seclusion', pos: 'idiom' },
      { zh: '经世致用', pinyin: 'jīng shì zhì yòng', en: 'scholarship applied to practical statecraft', pos: 'saying' },
      { zh: '知足常乐', pinyin: 'zhī zú cháng lè', en: 'contentment brings lasting happiness', pos: 'saying' },
      { zh: '上善若水', pinyin: 'shàng shàn ruò shuǐ', en: 'the highest good is like water (Laozi)', pos: 'saying' },
      { zh: '大道至简', pinyin: 'dà dào zhì jiǎn', en: 'the greatest truths are the simplest', pos: 'saying' },
      { zh: '和而不同', pinyin: 'hé ér bù tóng', en: 'harmony without uniformity', pos: 'saying' },
    ],
    10: [
      // Precision vocabulary for nuanced expression
      { zh: '微妙', pinyin: 'wēi miào', en: 'subtle / delicate / nuanced', pos: 'adj' },
      { zh: '恰到好处', pinyin: 'qià dào hǎo chù', en: 'just right / perfectly apt', pos: 'idiom' },
      { zh: '模棱两可', pinyin: 'mó léng liǎng kě', en: 'ambiguous / equivocal', pos: 'idiom' },
      { zh: '言简意赅', pinyin: 'yán jiǎn yì gāi', en: 'concise and comprehensive', pos: 'idiom' },
      { zh: '回味无穷', pinyin: 'huí wèi wú qióng', en: 'endlessly thought-provoking / lingering aftertaste', pos: 'idiom' },
      { zh: '耐人寻味', pinyin: 'nài rén xún wèi', en: 'thought-provoking / worth pondering', pos: 'idiom' },
      { zh: '入木三分', pinyin: 'rù mù sān fēn', en: 'incisive / penetrating analysis', pos: 'idiom' },
      { zh: '力透纸背', pinyin: 'lì tòu zhǐ bèi', en: 'forceful writing / power that comes through the page', pos: 'idiom' },
      { zh: '浑然天成', pinyin: 'hún rán tiān chéng', en: 'naturally perfect / as if formed by nature', pos: 'idiom' },
      { zh: '游刃有余', pinyin: 'yóu rèn yǒu yú', en: 'handle with ease / room to spare', pos: 'idiom' },
      { zh: '出神入化', pinyin: 'chū shén rù huà', en: 'consummate skill / reach the acme of perfection', pos: 'idiom' },
      { zh: '炉火纯青', pinyin: 'lú huǒ chún qīng', en: 'bring to perfection / highly skilled', pos: 'idiom' },
      { zh: '行云流水', pinyin: 'xíng yún liú shuǐ', en: 'flowing naturally / effortless style', pos: 'idiom' },
      { zh: '点石成金', pinyin: 'diǎn shí chéng jīn', en: 'turn the ordinary into something brilliant', pos: 'idiom' },
      { zh: '字字珠玑', pinyin: 'zì zì zhū jī', en: 'every word is a gem / perfectly crafted writing', pos: 'idiom' },
    ],
  },
}

/**
 * Returns the target vocabulary for the given language level and sub-level.
 * Returns an empty array if no list is defined.
 */
export function getVocab(level: string, sublevel: number): VocabItem[] {
  return CHINESE_VOCAB[level]?.[sublevel] ?? []
}

/**
 * Formats vocab items as a compact string for prompt injection.
 * Example: "你好 (nǐ hǎo) – hello; 再见 (zài jiàn) – goodbye"
 */
export function formatVocabForPrompt(words: VocabItem[]): string {
  return words.map((w) => `${w.zh} (${w.pinyin}) – ${w.en}`).join('; ')
}
